# 应用名称，将会显示在Eureka界面的应用名称列
spring:
  application:
    name: cloud-blog-zuul
  # 应用端口
server:
  port: 28761

zuul:
  routes:
    cloud-blog-admin:
      path: /sys/**


eureka:
  instance:
    # 服务名，默认取 spring.application.name 配置值，如果没有则为 unknown
    appname: cloud-blog-zuul
  client:
    # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为 http://localhost:8761/eureka
    # 如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
    serviceUrl:
      defaultZone: http://register-center-1:8761/eureka,http://register-center-2:8762/eureka,http://register-center-3:8763/eureka
    # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

    # 是否向注册中心注册自己，缺省：true
    # 一般情况下，Eureka服务端是不需要再注册自己的
    registerWithEureka: true
    # 是否从Eureka获取注册信息，缺省：true
    # 一般情况下，Eureka服务端是不需要的
    fetchRegistry: true
    #
    enabled: true


logging:
    file: log/cloud-blog-zuul.log
    level:
      com.lgcy.blog.cloudblog.*: debug