# 应用名称，将会显示在Eureka界面的应用名称列
spring:
  application:
    name: cloud-blog-register-center
  # 应用端口，Eureka服务端默认为：8761
server:
  port: 8761

eureka:
  instance:
    # 服务名，默认取 spring.application.name 配置值，如果没有则为 unknown
    appname: cloud-blog-register-center
    # 应用实例主机名
    # hosts 文件里添加映射 127.0.0.1       register-center-1
    hostname: register-center-1
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    prefer-ip-address: false
    # 服务失效时间，失效的服务将被剔除。单位：秒，默认：90
    lease-expiration-duration-in-seconds: 90
    # 服务续约（心跳）频率，单位：秒，缺省30
    lease-renewal-interval-in-seconds: 30
  client:
    # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为 http://localhost:8761/eureka
    # 如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
    serviceUrl:
      defaultZone: http://register-center-1:8761/eureka,http://register-center-2:8762/eureka,http://register-center-3:8763/eureka
    # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

    # 是否向注册中心注册自己，缺省：true
    # 一般情况下，Eureka服务端是不需要再注册自己的
    registerWithEureka: true
    # 是否从Eureka获取注册信息，缺省：true
    # 一般情况下，Eureka服务端是不需要的
    fetchRegistry: true

  server:
    waitTimeInMsWhenSyncEmpty: 0
    # 是否允许开启自我保护模式，缺省：true
    # 当Eureka服务器在短时间内丢失过多客户端时，自我保护模式可使服务端不再删除失去连接的客户端
    enable-self-preservation: true
    # Eureka服务器清理无效节点的时间间隔，单位：毫秒，缺省：60000，即60秒
    eviction-interval-timer-in-ms: 60000

logging:
    file: log/cloud-blog-register-center.log
    level:
      com.lgcy.blog.cloudblog.*: debug